name: Problem with wiki
description: Any problems with wiki
title: "⚠️ Invalid"
body:
  - type: markdown
    attributes:
      value: "Wiki realted issues located [here](https://github.com/StoryAnvil/ResourcesAndIssues/issues/new?assignees=&labels=Project%3A+WIKI&projects=&template=WikiReport.yml&title=%5BWIKI%5D+%3Ctitle+here%3E)."
  - type: input
    id: prevent1
    attributes:
      label: ⚠️ Do not touch this!
      description: Click [here](https://github.com/StoryAnvil/ResourcesAndIssues/issues/new?assignees=&labels=Project%3A+WIKI&projects=&template=WikiReport.yml&title=%5BWIKI%5D+%3Ctitle+here%3E) to create issue.
      placeholder: 🤐 do not write anything here!
    validations:
      required: true
  - type: checkboxes
    id: prevent2
    attributes:
      label: ⚠️ Do not touch this!
      description: WIKI RELATED ISSUES LOCATED IN ResourcesAndIssues REPO!!!
      options:
        - label: I creating this issue knowing it will be ingored and I might be blocked from interacting with StoryAnvil resources
          required: true
        - label: I get so there isn't single point in creating issue here
          required: true
        - label: I want create this issue even knowing so it will be ignored
          required: true
        - label: I am person who creating useless issue becouse it will be absolutly ignored
          required: true
        - label: Yeah, I know you will block me from creating issues
          required: true
        - label: This issue has no meaning
          required: true
        - label: This issue should be deleted
          required: true
        - label: There is no point in creating this
          required: true