name: IssueCreationCheckout

on:
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
          gh issue comment $ISSUE --body "This issue was tranfered from Wiki repository. Please do not create issues there!"
          gh issue transfer $ISSUE StoryAnvil/ResourcesAndIssues