name: IssueCreationCheckout

on:
  issues:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
        run: |
          gh issue delete $ISSUE --yes